repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        name: End of File Fixer
      - id: trailing-whitespace
        name: Trailing Whitespace Fixer
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.9.9
    hooks:
      - id: prettier
        name: Pretty Markdown
        args: [--prose-wrap=always]
        types_or: [markdown, yaml]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        name: PyUpgrade
  - repo: https://github.com/psf/black
    rev: 26.10.0
    hooks:
      - id: black
        name: Black
        language_version: python3
        entry: black
        types_or: [python, pyi]
        require_serial: true
        minimum_pre_commit_version: 2.9.2
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        name: Gitleaks Scanner
